sonar.projectKey=taysir
sonar.organization=ahmedchoulak2004
sonar.projectName=Taysir
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts,src/__tests__/**/*.test.tsx
sonar.exclusions=node_modules/**, .next/**, coverage/**, public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
